config/routes.rb
Rails.application.routes.draw do
  get 'experiments/page1'

  get 'experiments/page2'

  get 'experiments/page3'
	
  get 'pages/batman'

  get 'pages/superman'

  post 'vote/batman'

  post 'vote/superman'

  root 'pages#batman_vs_superman'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vote_batman.rb
class VoteBatman < ApplicationRecord
end

app/models/vote_superman.rb
class VoteSuperman < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController

  def page1
  end

  def page2
  	render layout: "bootstrap"
  end

  def page3
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def batman
  end

  def superman
  end

  def batman_vs_superman
  end

  def save_vote_superman
    Votesuperman.create(name: params[:name], email: params[:email])
    redirect_to pages_batman_vs_superman_path, notice: 'Tu voto ha sido registrado con exito!'
  end

  def save_vote_batman
    Votebatman.create(name: params[:name], email: params[:email])
    redirect_to pages_batman_vs_superman_path, notice: 'Tu voto ha sido registrado con exito!'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/experiments/page1.html.erb
<%= image_tag "Dragon-Ball-Z-Extreme-Budoten.jpg" %>

app/views/experiments/page2.html.erb
<h1>Experiments#page2</h1>
<p>Find me in app/views/experiments/page2.html.erb</p>

app/views/experiments/page3.html.erb
<body class="experiments-page3">
  <h1>Experiments#page3</h1>
  <p>Find me in app/views/experiments/page3.html.erb</p>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Superheroes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/batman.html.erb
<h1 class="superheroe">I am Batman</h1>

<script>
    $.backstretch("https://static-latercera-qa.s3.amazonaws.com/wp-content/uploads/sites/7/20150429/2108594.jpg");
</script>

app/views/pages/batman_vs_superman.html.erb
<div class="container">

  <div class="superman">
    <a class="superheroe" href="<%= pages_superman_url %>">Superman</a>
    <%=image_tag("superman.jpg", class:"img-responsive")%>

    <div class="form-superman">
      <form action="<%= pages_save_votesuperman_path %>" method="POST">
      <input placeholder="nombre" type="text" name="name" value="">
      <input placeholder="email" type="email" name="email" value="">
      <input type="submit" name="enviar" value="enviar">
      </form>
    </div>

  </div>
  <div class="batman">
    <a class="superheroe" href="<%= pages_batman_url %>">Batman</a>
    <%=image_tag("batman.jpg", class:"img-responsive")%>

    <div class="form-batman">
      <form action="<%= pages_save_votebatman_path %>" method="POST">
      <input placeholder="nombre" type="text" name="name" value="">
      <input placeholder="nombre" type="email" name="email" value="">
      <input type="submit" name="enviar" value="enviar">
      </form>
    </div>

  </div>

  <%=flash[:notice]%>

</div>

app/views/pages/superman.html.erb
<h1 class="superheroe">This looks like a job for Superman</h1>

<script>
    $.backstretch("http://image.vanguardia.com.mx/sites/default/files/superman-3d-art.jpg");
</script>